[tools]
# Install latest selene
selene = { source = "Kampfkarren/selene", version = "x" }
rojo = { source = "rojo-rbx/rojo", version = "6.0.0-rc.4" }
remodel = { source = "rojo-rbx/remodel", version = "0.7.1"}
