gitRepoUrl = "https://github.com/Sleitnick/Knit"

classOrder = [
	"KnitServer",
	"KnitClient"
]

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "Lightweight game framework for Roblox"
favicon = "/img/favicon.png"
