name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install foreman
    - uses: Roblox/setup-foreman@v1
      with:
          version: "^1.0.0"
          token: ${{ SECRETS.GITHUB_TOKEN }}
    - name: Lint
      run: |
        selene ./
