name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Selene
      run: |
        wget -q -O selene https://github.com/Kampfkarren/selene/releases/latest/download/selene-linux
        chmod +x ./selene
    - name: Lint
      run: |
        ./selene ./